config/routes.rb
Rails.application.routes.draw do
  get "may1" => "may2018#may1"
  get "may2" => "may2018#may2"
  get "may3" => "may2018#may3"
  get "may4" => "may2018#may4"
  get "may5" => "may2018#may5"
  get "may6" => "may2018#may6"
  get "may7" => "may2018#may7"
  get "may8" => "may2018#may8"
  get "may9" => "may2018#may9"
  get "may10" => "may2018#may10"
  get "may11" => "may2018#may11"
  get "may12" => "may2018#may12"
  get "may13" => "may2018#may13"
  get "may14" => "may2018#may14"
  get "may15" => "may2018#may15"
  get "may16" => "may2018#may16"
  get "may17" => "may2018#may17"
  get "may18" => "may2018#may18"
  get "may19" => "may2018#may19"
  get "may20" => "may2018#may20"
  get "may21" => "may2018#may21"
  get "may22" => "may2018#may22"
  get "may23" => "may2018#may23"
  get "may24" => "may2018#may24"
  get "may25" => "may2018#may25"
  get "may26" => "may2018#may26"
  get "may27" => "may2018#may27"
  get "may28" => "may2018#may28"
  get "may29" => "may2018#may29"
  get "may30" => "may2018#may30"
  get "may31" => "may2018#may31"

  get "apr1" => "april2018#apr1"
  get "apr2" => "april2018#apr2"
  get "apr3" => "april2018#apr3"
  get "apr4" => "april2018#apr4"
  get "apr5" => "april2018#apr5"
  get "apr6" => "april2018#apr6"
  get "apr7" => "april2018#apr7"
  get "apr8" => "april2018#apr8"
  get "apr9" => "april2018#apr9"
  get "apr10" => "april2018#apr10"
  get "apr11" => "april2018#apr11"
  get "apr12" => "april2018#apr12"
  get "apr13" => "april2018#apr13"
  get "apr14" => "april2018#apr14"
  get "apr15" => "april2018#apr15"
  get "apr16" => "april2018#apr16"
  get "apr17" => "april2018#apr17"
  get "apr18" => "april2018#apr18"
  get "apr19" => "april2018#apr19"
  get "apr20" => "april2018#apr20"
  get "apr21" => "april2018#apr21"
  get "apr22" => "april2018#apr22"
  get "apr23" => "april2018#apr23"
  get "apr24" => "april2018#apr24"
  get "apr25" => "april2018#apr25"
  get "apr26" => "april2018#apr26"
  get "apr27" => "april2018#apr27"
  get "apr28" => "april2018#apr28"
  get "apr29" => "april2018#apr29"
  get "apr30" => "april2018#apr30"

  get "mar1" => "march2018#mar1"
  get "mar2" => "march2018#mar2"
  get "mar3" => "march2018#mar3"
  get "mar4" => "march2018#mar4"
  get "mar5" => "march2018#mar5"
  get "mar6" => "march2018#mar6"
  get "mar7" => "march2018#mar7"
  get "mar8" => "march2018#mar8"
  get "mar9" => "march2018#mar9"
  get "mar10" => "march2018#mar10"
  get "mar11" => "march2018#mar11"
  get "mar12" => "march2018#mar12"
  get "mar13" => "march2018#mar13"
  get "mar14" => "march2018#mar14"
  get "mar15" => "march2018#mar15"
  get "mar16" => "march2018#mar16"
  get "mar17" => "march2018#mar17"
  get "mar18" => "march2018#mar18"
  get "mar19" => "march2018#mar19"
  get "mar20" => "march2018#mar20"
  get "mar21" => "march2018#mar21"
  get "mar22" => "march2018#mar22"
  get "mar23" => "march2018#mar23"
  get "mar24" => "march2018#mar24"
  get "mar25" => "march2018#mar25"
  get "mar26" => "march2018#mar26"
  get "mar27" => "march2018#mar27"
  get "mar28" => "march2018#mar28"
  get "mar29" => "march2018#mar29"
  get "mar30" => "march2018#mar30"
  get "mar31" => "march2018#mar31"

  get "feb1" => "february2018#feb1"
  get "feb2" => "february2018#feb2"
  get "feb3" => "february2018#feb3"
  get "feb4" => "february2018#feb4"
  get "feb5" => "february2018#feb5"
  get "feb6" => "february2018#feb6"
  get "feb7" => "february2018#feb7"
  get "feb8" => "february2018#feb8"
  get "feb9" => "february2018#feb9"
  get "feb10" => "february2018#feb10"
  get "feb11" => "february2018#feb11"
  get "feb12" => "february2018#feb12"
  get "feb13" => "february2018#feb13"
  get "feb14" => "february2018#feb14"
  get "feb15" => "february2018#feb15"
  get "feb16" => "february2018#feb16"
  get "feb17" => "february2018#feb17"
  get "feb18" => "february2018#feb18"
  get "feb19" => "february2018#feb19"
  get "feb20" => "february2018#feb20"
  get "feb21" => "february2018#feb21"
  get "feb22" => "february2018#feb22"
  get "feb23" => "february2018#feb23"
  get "feb24" => "february2018#feb24"
  get "feb25" => "february2018#feb25"
  get "feb26" => "february2018#feb26"
  get "feb27" => "february2018#feb27"
  get "feb28" => "february2018#feb28"

  get "jan1" => "january2018#jan1"
  get "jan2" => "january2018#jan2"
  get "jan3" => "january2018#jan3"
  get "jan4" => "january2018#jan4"
  get "jan5" => "january2018#jan5"
  get "jan6" => "january2018#jan6"
  get "jan7" => "january2018#jan7"
  get "jan8" => "january2018#jan8"
  get "jan9" => "january2018#jan9"
  get "jan10" => "january2018#jan10"
  get "jan11" => "january2018#jan11"
  get "jan12" => "january2018#jan12"
  get "jan13" => "january2018#jan13"
  get "jan14" => "january2018#jan14"
  get "jan15" => "january2018#jan15"
  get "jan16" => "january2018#jan16"
  get "jan17" => "january2018#jan17"
  get "jan18" => "january2018#jan18"
  get "jan19" => "january2018#jan19"
  get "jan20" => "january2018#jan20"
  get "jan21" => "january2018#jan21"
  get "jan22" => "january2018#jan22"
  get "jan23" => "january2018#jan23"
  get "jan24" => "january2018#jan24"
  get "jan25" => "january2018#jan25"
  get "jan26" => "january2018#jan26"
  get "jan27" => "january2018#jan27"
  get "jan28" => "january2018#jan28"
  get "jan29" => "january2018#jan29"
  get "jan30" => "january2018#jan30"
  get "jan31" => "january2018#jan31"

  get "dec1" => "december2017#dec1"
  get "dec2" => "december2017#dec2"
  get "dec3" => "december2017#dec3"
  get "dec4" => "december2017#dec4"
  get "dec5" => "december2017#dec5"
  get "dec6" => "december2017#dec6"
  get "dec7" => "december2017#dec7"
  get "dec8" => "december2017#dec8"
  get "dec9" => "december2017#dec9"
  get "dec10" => "december2017#dec10"
  get "dec11" => "december2017#dec11"
  get "dec12" => "december2017#dec12"
  get "dec13" => "december2017#dec13"
  get "dec14" => "december2017#dec14"
  get "dec15" => "december2017#dec15"
  get "dec16" => "december2017#dec16"
  get "dec17" => "december2017#dec17"
  get "dec18" => "december2017#dec18"
  get "dec19" => "december2017#dec19"
  get "dec20" => "december2017#dec20"
  get "dec21" => "december2017#dec21"
  get "dec22" => "december2017#dec22"
  get "dec23" => "december2017#dec23"
  get "dec24" => "december2017#dec24"
  get "dec25" => "december2017#dec25"
  get "dec26" => "december2017#dec26"
  get "dec27" => "december2017#dec27"
  get "dec28" => "december2017#dec28"
  get "dec29" => "december2017#dec29"
  get "dec30" => "december2017#dec30"
  get "dec31" => "december2017#dec31"


  resources :apps
  get "history" => "apps#history" 
  get "about" => "apps#about"
  get "index" => "apps#index" 
  get "december2017" => "apps#december2017" 
  get "january2018" => "apps#january2018" 
  get "february2018" => "apps#february2018" 
  get "march2018" => "apps#march2018" 
  get "april2018" => "apps#april2018" 
  get "may2018" => "apps#may2018"
  get "june2018" => "apps#june2018" 
  get "july2018" => "apps#june2018" 
  get "august2018" => "apps#june2018" 
  get "september2018" => "apps#june2018" 
  get "october2018" => "apps#june2018" 
  get "november2018" => "apps#june2018" 
  get "december2018" => "apps#june2018" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SOLAR ENERGY HARVESTING with LIGHT EMITTING DIODE II</title>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Play:700,400' type='text/css'>


      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
      <script src="http://d3js.org/d3.v3.min.js" language="JavaScript"></script>
      <script src="https://cdn.zingchart.com/zingchart.min.js"></script>

      <!--  jQuery -->
      <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

      <!-- Isolated Version of Bootstrap, not needed if your site already uses Bootstrap -->
      <link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />

      <!-- Bootstrap Date-Picker Plugin -->
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>



      <link href="default.css" rel="stylesheet" type="text/css" media="all" />
      <link href="https://fonts.googleapis.com/css?family=Athiti|Noto+Sans" rel="stylesheet">

      <%= csrf_meta_tags %>
      <%= javascript_include_tag "liquidFillGauge", "data-turbolinks-track" => true  %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>

  <body>
    <div class="header text-center">
      <h1>SOLAR ENERGY HARVESTING WITH LIGHT EMITTING DIODE II</h1>
      <a class="link-active>"<%= link_to "<span>Dashboard</span>".html_safe, index_path %></a>
      <span> | </span>
      <%= link_to "<span>History</span>".html_safe, history_path %>
      <span> | </span>
      <%= link_to "<span>About Project</span>".html_safe, about_path %>
    </div>
    <div class="container-fluid">
      <%= yield %>
    </div>

<!--Date and time -->
    <script>
      var today = new Date();
      var dd = today.getDate();
      var mm = today.getMonth()+1; //January is 0!
      var yyyy = today.getFullYear();
      if(dd<10) {
        dd='0'+dd
      } 

      if(mm<10) {
        mm='0'+mm
      } 
      today = mm+'/'+dd+'/'+yyyy;
      document.getElementById("date").innerHTML = today;
      var myVar=setInterval(function(){myTimer()},1000);
      function myTimer() {
        var d = new Date();
        document.getElementById("timenav").innerHTML = d.toLocaleTimeString();
      }
    </script>
  </body>
</html>